CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    MATRICULA VARCHAR(20) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    SENHA VARCHAR(100) NOT NULL,
    TIPO_PERMISSAO INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS BOOLEAN DEFAULT TRUE
);
