CREATE TABLE REGISTRO_PONTO (
    ID_PONTO SERIAL PRIMARY KEY,
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO),
    ID_TIPO_PONTO INT REFERENCES TIPO_PONTO(ID_TIPO_PONTO),
    DATA_HORA TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
