CREATE TABLE USUARIO_SETOR (
    ID_VINCULO_SETOR SERIAL PRIMARY KEY,
    ID_SETOR INT REFERENCES SETOR(ID_SETOR),
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
