CREATE TABLE TIPO_PERMISSAO (
    ID_PERMISSAO SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
