CREATE TABLE USUARIO_TURNO (
    ID_VINCULO_TURNO SERIAL PRIMARY KEY,
    ID_TURNO INT REFERENCES TURNO(ID_TURNO),
    ID_USUARIO INT REFERENCES USUARIO(ID_USUARIO),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
